[tool.poetry]
name = "Audiobooks"
version = "0.4.5"
description = "My audiobook library program."
authors = ["Robert Poulin <poulin.robert@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/RLPoulin/Audiobooks"

[tool.poetry.dependencies]
python = "^3.8.0"
flask = "^1.1.1"
flask-sqlalchemy = "^2.4.1"
sqlalchemy = "^1.3.11"

[tool.poetry.dev-dependencies]
colorama = "^0.4.3"
commitizen = "^2.4.0"
flakehell = "^0.3.3"
ipython = "^7.20.0"
mypy = "^0.761"
pre-commit = "^2.7.1"
sqlalchemy-stubs = "^0.3"
wemake-python-styleguide = "^0.14.1"


[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.5"
tag_format = "v$version"
version_files = [
    "pyproject.toml:version",
    "audiobooks/__init__.py"
]


[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.mypy_cache
  | \.venv
  | __pycache__
  | build
  | dist
)/
'''


[tool.isort]
profile = "black"


[tool.flakehell]
exclude = [
    ".eggs",
    ".git",
    ".mypy_cache",
    ".venv",
    "__pycache__"
]
format = "grouped"
show_source = true
statistics = false
doctests = true
enable_extensions = "G"

accept_encodings = "utf-8"
max_complexity = 6
max_line_length = 88
radon_max_cc = 10
radon_show_closures = true
radon_no_assert = true

[tool.flakehell.plugins]
"flake8-*" = ["+*"]
flake8-coding = ["+*", "-C101", "-C812"]
flake8-commas = ["-*"]
flake8-darglint = ["-*"]  # enable when docstrings are mostly done
flake8-docstrings = ["+*", "-D105"]
flake8-quotes = ["-*"]
flake8-print = ["-*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-E203", "-W503"]
pyflakes = ["+*"]
pylint = ["+*"]
radon = ["+*"]
wemake-python-styleguide = [
    "+*",
    "-WPS305",
    "-WPS407",
    "-WPS410",
    "-WPS412",
]

[tool.flakehell.exceptions."audiobooks/models.py"]
wemake-python-styleguide = ["-WPS601"]

[tool.flakehell.exceptions."audiobooks/db_tests.py"]
wemake-python-styleguide = ["-WPS226", "-WPS432"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
