[tool.poetry]
name = "Audiobooks"
version = "0.4.3"
description = "My audiobook library program."
authors = ["Robert Poulin <poulin.robert@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.8"
sqlalchemy = "^1.3.11"
flask = "^1.1.1"
flask-sqlalchemy = "^2.4.1"
colorama = "^0.4.3"

[tool.poetry.dev-dependencies]
ipython = "^7.10.2"
black = "^19.10b0"
bump2version = "^1.0.0"
mypy = "^0.761"
sqlalchemy-stubs = "^0.3"
flakehell = "^0.3.3"
wemake-python-styleguide = "^0.13.4"


[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(.+\.egg-info | \.git | \.venv | \.idea)/
  | __pycache__
)
'''


[tool.flakehell]
exclude = [".git", ".mypy_cache", ".venv", "__pycache__"]
format = "grouped"
show_source = true
statistics = false
doctests = true
enable_extensions = "G"

accept_encodings = "utf-8"
max_complexity = 6
max_line_length = 88
radon_max_cc = 10
radon_show_closures = true
radon_no_assert = true

[tool.flakehell.plugins]
"flake8-*" = ["+*"]
flake8-coding = ["+*", "-C101", "-C812"]
flake8-darglint = ["-*"]  # enable when docstrings are mostly done
flake8-docstrings = ["+*", "-D105"]
flake8-isort = ["-*"]
flake8-quotes = ["-*"]
flake8-print = ["-*"]
mccabe = ["+*"]
nitpick = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*"]
pyflakes = ["+*"]
radon = ["+*"]
wemake-python-styleguide = [
    "+*",
    "-WPS305",
    "-WPS407",
    "-WPS410",
    "-WPS412",
    "-WPS601",  # for models.py, enable when per-file exclusions are available
]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
